sudo: required
language: objective-c 
osx_image: xcode7.3 

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gem
  - $HOME/.rvm
  - $HOME/.cocoapods
  - samples/client/petstore/objc/default/SwaggerClientTests/Pods

services:
  - docker

addons:
  hosts:
    - petstore.swagger.io

before_install:
   - rvm list
   - rvm install 2.2.2 > /dev/null 2>&1
   - rvm use 2.2.2
   - sudo gem install cocoapods
   - pod --version
   - pod setup > /dev/null 2>&1
   - brew install xctool
   - git clone https://github.com/swagger-api/swagger-samples
   - cd swagger-samples/java/java-jersey-jaxrs && sudo mvn jetty:run &

install:

script:
   - cd samples/client/petstore/objc/default/SwaggerClientTests && pod install && xctool -workspace "SwaggerClient.xcworkspace" -scheme "SwaggerClient-Example" -destination "platform:iOS Simulator,OS:8.1,name:iPhone 5s" test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

env:
  - DOCKER_IMAGE_NAME=swaggerapi/swagger-generator
